POST http://localhost:8000/signup/
Content-Type: application/json

{
    "email": "sanjangeetsingh65@gmail.com",
    "password": "DragonHunter123",
    "full_name": "Sam",
    "otp": "369644"
}

###

POST http://localhost:8000/signup/request-otp/
Content-Type: application/json

{
    "email": "sanjangeetsingh65@gmail.com"
}

###

POST http://localhost:8000/login/renew/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1MzIyODU3NywiaWF0IjoxNzUwNjM2NTc3LCJqdGkiOiI2NjY0MzcyMzg2MGU0Yjg5YmVkZWM1ZjRjOTlkMGU5NCIsInVzZXJfaWQiOjJ9.QlsaAz-CE93TJwTaKqmTLqsmBpRiC_N1moG3cAQ9mCA"
}

###

POST http://localhost:8000/login/
Content-Type: application/json

{
    "email": "sanjangeetsingh25@gmail.com",
    "password": "DragonHunter123"
}

###

GET http://localhost:8000/user/info/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNzI0MjM4LCJpYXQiOjE3NTA3MjA2MzgsImp0aSI6IjZjMzA2ZWM0ZjljZjQyZDBhZjNhZGUyNmIyNzllYjNlIiwidXNlcl9pZCI6M30.04KbnjHdhbBjP4wTrtD6vv-i4AJZ3Oqf53pF_sEYeAU

###

POST http://localhost:8000/user/update/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjQwMTc3LCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjhiZjgwZmNmMTAyMzRmYWU4NTE2YzVkZmNlODZmNTZiIiwidXNlcl9pZCI6Mn0.ylsJzuEI5k2z8FjFqt8C6HxNzCx0-CE_axM441eE73E

{
    "full_name": "Sanjangeet Singh"
}

###

POST http://localhost:8000/user/change-password/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjQwMTc3LCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjhiZjgwZmNmMTAyMzRmYWU4NTE2YzVkZmNlODZmNTZiIiwidXNlcl9pZCI6Mn0.ylsJzuEI5k2z8FjFqt8C6HxNzCx0-CE_axM441eE73E

{
    "old_password": "DragonHunter123",
    "new_password": "KingSlayer285"
}

###

POST http://localhost:8000/reset-password/
Content-Type: application/json

{
    "email": "sanjangeetsingh65@gmail.com",
    "otp": "369644",
    "password": "DragonHunter123"
}

###

GET http://localhost:8000/groups/?search=Mono
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjk2NTUxLCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjA3ZTU1NWZhZDQ4NzQzNDU5NmVkMDgzMjliYWE0ODVmIiwidXNlcl9pZCI6Mn0.JMA8N49F5rEKSLkv-0_pGNp094ty7a51kysPrlbdURs

###

POST http://localhost:8000/groups/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjk2NTUxLCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjA3ZTU1NWZhZDQ4NzQzNDU5NmVkMDgzMjliYWE0ODVmIiwidXNlcl9pZCI6Mn0.JMA8N49F5rEKSLkv-0_pGNp094ty7a51kysPrlbdURs
Content-Type: application/json

{
    "name": "Monoblade Technologies"
}

###

PATCH http://localhost:8000/groups/2/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjk2NTUxLCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjA3ZTU1NWZhZDQ4NzQzNDU5NmVkMDgzMjliYWE0ODVmIiwidXNlcl9pZCI6Mn0.JMA8N49F5rEKSLkv-0_pGNp094ty7a51kysPrlbdURs
Content-Type: application/json

{
    "name": "Monoblade Studios"
}

###

GET http://localhost:8000/groups/my/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNjk2NTUxLCJpYXQiOjE3NTA2MzY1NzcsImp0aSI6IjA3ZTU1NWZhZDQ4NzQzNDU5NmVkMDgzMjliYWE0ODVmIiwidXNlcl9pZCI6Mn0.JMA8N49F5rEKSLkv-0_pGNp094ty7a51kysPrlbdURs

###

POST http://localhost:8000/posts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNzI0MjM4LCJpYXQiOjE3NTA3MjA2MzgsImp0aSI6IjZjMzA2ZWM0ZjljZjQyZDBhZjNhZGUyNmIyNzllYjNlIiwidXNlcl9pZCI6M30.04KbnjHdhbBjP4wTrtD6vv-i4AJZ3Oqf53pF_sEYeAU

{
    "title": "Hello, World!",
    "content": "Hello, World!",
    "group": 1
}

###

GET http://localhost:8000/posts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzUwNzI0MjM4LCJpYXQiOjE3NTA3MjA2MzgsImp0aSI6IjZjMzA2ZWM0ZjljZjQyZDBhZjNhZGUyNmIyNzllYjNlIiwidXNlcl9pZCI6M30.04KbnjHdhbBjP4wTrtD6vv-i4AJZ3Oqf53pF_sEYeAU

